pipeline {
    agent any
    stages {
        stage('pre_validation') {
            steps {
                script {
                    slackSend channel: '#network-automation', message: "Build Started : ${env.JOB_NAME}  ${env.BUILD_NUMBER}  (<${env.BUILD_URL}|Open>)"
                    slackSend channel: '#network-automation', message: "stage: pre_validation : ${env.JOB_NAME}  ${env.BUILD_NUMBER}  (<${env.BUILD_URL}|Open>)"
                    withCredentials([usernamePassword(credentialsId: 'cisco_pass', passwordVariable: 'GNS3_PASS', usernameVariable: 'GNS3_UNAME')]) {
                        sh 'rm -rf projects/ibgp/output'
                        sh 'mkdir -p projects/ibgp/output'
                        sh 'mkdir projects/ibgp/output/pre_validation'
                        sh 'mkdir projects/ibgp/output/post_validation'
                        sh 'mkdir projects/ibgp/output/configuration'
                        sh 'cd projects/ibgp/output && ls'
                        sh 'python3 projects/ibgp/python_scripts/pre_validation.py'
                    }
                }
            }
        }
        stage('configure') {
            steps {
                slackSend channel: '#network-automation', message: "stage: configuration : ${env.JOB_NAME}  ${env.BUILD_NUMBER}  (<${env.BUILD_URL}|Open>)"
                script {
                    withCredentials([usernamePassword(credentialsId: 'cisco_pass', passwordVariable: 'GNS3_PASS', usernameVariable: 'GNS3_UNAME')]) {
                        sh 'python3 projects/ibgp/python_scripts/config_bgp.py'
                    }
                }
            }
        }
        stage('post_validation') {
            steps {
                 slackSend channel: '#network-automation', message: "post_validation : ${env.JOB_NAME}  ${env.BUILD_NUMBER}  (<${env.BUILD_URL}|Open>)"
                script {
                    withCredentials([usernamePassword(credentialsId: 'cisco_pass', passwordVariable: 'GNS3_PASS', usernameVariable: 'GNS3_UNAME')]) {
                        sh 'python3 projects/ibgp/python_scripts/post_validation.py'
                        sh 'zip -r changeReq123_output.zip projects/ibgp/output'
                        archiveArtifacts artifacts: 'changeReq123_output.zip'
                        cleanWs()
                    }
                }
            }
        }
    }
    post {
        success {
            slackSend channel: '#network-automation', message: "Build Successfully deployed!: ${env.JOB_NAME}  ${env.BUILD_NUMBER}  (<${env.BUILD_URL}|Open>)", color: "good"
        }
        failure {
            slackSend channel: '#network-automation', message: "Build failed: ${env.JOB_NAME}  ${env.BUILD_NUMBER}  (<${env.BUILD_URL}|Open>)", color: "danger"
        }
    }
}
